// Bundles the modular Rev F source into a single self-contained HTML file
// (rev-f.html) that runs over file:// with no server, like the original
// model3d.html. Three.js is reused from the inline copy already vendored in
// this repo's food-cutter/model3d.html, so no CDN or npm install is needed.
//
// Run: node scripts/build.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const repoFood = join(root, '..'); // food-cutter/

// --- extract the inline THREE module from the existing model3d.html --------
const model3d = readFileSync(join(repoFood, 'model3d.html'), 'utf8');
const threeMatch = model3d.match(/(\/\* ==== THREE\.JS r160[\s\S]*?)\/\* ==== DicePod sequence ==== \*\//);
if (!threeMatch) throw new Error('could not locate inline THREE source in model3d.html');
const threeSource = threeMatch[1];

// --- strip module syntax from our sources, in dependency order -------------
function strip(src) {
  return src
    .replace(/^import[^;]*;\s*$/gm, '')           // drop imports
    .replace(/^export\s+default\s+/gm, '')
    .replace(/^export\s+(?=(const|let|var|function|class))/gm, '')
    .replace(/^export\s*\{[^}]*\};?\s*$/gm, '');  // drop export lists
}

const files = ['config.js', 'stateMachine.js', 'scene.js', 'ui.js', 'app.js'];
const appSrc = files
  .map(f => `\n/* ===== ${f} ===== */\n` + strip(readFileSync(join(root, 'src/animation', f), 'utf8')))
  .join('\n');

// dev module (unbundled) keeps real imports for a module server workflow
const devBundle = `import * as THREE from './three.module.js';\n${appSrc}\nstartApp(document.getElementById('app'));\n`;
writeFileSync(join(root, 'app.bundle.js'), devBundle);
writeFileSync(join(root, 'three.module.js'), threeSource + '\nexport default THREE;\n');

// self-contained single file
const inline = `/* Rev F — self-contained build. Generated by scripts/build.mjs. */\n${threeSource}\n${appSrc}\nstartApp(document.getElementById('app'));\n`;
const html = readFileSync(join(root, 'index.html'), 'utf8')
  .replace('<script type="module" src="./app.bundle.js"></script>',
           () => `<script>\n${inline.replace(/<\/script>/g, '<\\/script>')}\n</script>`);
writeFileSync(join(root, 'rev-f.html'), html);
console.log('built rev-f.html (%d KB) + app.bundle.js + three.module.js', Math.round(html.length / 1024));
